### PR TITLE
chore: switch to pnpm

### PR DESCRIPTION
**Pull request by benmccann**
The e2e projects are testing against old versions of `svelte-jester`. This switches to use pnpm (which Svelte and SvelteKit use) in order to test against the current code instead of a published version

### CODE REVIEW

**Comment by sebastianrothe** [comment]
Thats why, both e2e test setups had this override to use the version from the workspace:
- https://github.com/svelteness/svelte-jester/blob/master/e2e/sveltekit/jest.config.json#L5
- https://github.com/svelteness/svelte-jester/blob/master/e2e/svelte/package.json#L35

I dont mind switching to pnpm though :)

**Review by sebastianrothe — APPROVED** [review]

**Comment by benmccann** [comment]
Ah, okay! Good to know. I saw the version being bumped in one of your PRs and it threw me a bit

I still have a bit of a preference for pnpm as it allows to just run `pnpm install` once vs having to run `npm install` in each project, so do you think we should go ahead and merge this since it sounds like you wouldn't mind the switch?

**Comment by benmccann** [comment]
Thanks @sebastianrothe! Just FYI, your two PRs will need to be updated to address the merge conflicts from this one

**Comment by sebastianrothe** [comment]
Yeah, I will address the conflicts tomorrow :)

**Pull request merged**
